config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :drivers, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  validates :color, presence: true
  validates :driver, presence: true
  COLORS = ['red', 'yellow']
  DRIVERS = ['Alex', 'Aline', 'Liz', 'Seigo', 'Tomo', 'Taku', 'Sho', 'Jess', 'Yuplin', 'Doug', 'Yann', 'Sylvain', 'Sasha', 'Noemi']
  KEYS = ['a', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'l', 'M', 'q', 'Z']
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :car, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to cars_path
    else
      render :new
    end
  end

  private

  def car_params
    params.require(:car).permit(:color, :driver, :key)
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def new
    @driver = Driver.new
  end

  def create
    @driver = Driver.new(driver_params)
    if @driver.save
      redirect_to cars_path
    else
      render :new
    end
  end

  private

  def driver_params
    params.require(:driver).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<div class="container title">

</div>
  <% @cars.each do |car| %>
    <div >
      <table class="racer-table">
      <tr id="player1-race">
        <td class="hidden-car active">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
        <td class="hidden-car">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
        <td class="hidden-car">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
        <td class="hidden-car">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
        <td class="hidden-car">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
        <td class="hidden-car">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
        <td class="hidden-car">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
        <td class="hidden-car">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
        <td class="hidden-car">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
        <td class="hidden-car">
          <div class="cars-card">
            <% if car.color == 'red' %>
              <%= image_tag "red.png", alt: "alttext", width: '150' %>
            <% elsif car.color == 'yellow' %>
              <%= image_tag "yellow.png", alt: "alttext", width: '150' %>
            <% end %>
            <div class="driver">
              <% if car.driver == 'Aline' %>
                <%= image_tag "aline.png", alt: "alttext", size: '50' %>
              <% elsif car.driver == 'Liz' %>
                <%= image_tag "liz.png", alt: "alttext", size: '50' %>
              <% end %>
            </div>
            <h3 class="car-key"><%= car.key.capitalize %></h3>
          </div>
        </td>
      </tr>
    </table>
    <hr>

      <br>
    </div>
  <% end %>



    <script src="main.js"></script>

app/views/cars/new.html.erb
<div class="container">
  <h2>Select a car</h2>
  <%= simple_form_for @car do |f| %>
    <%= f.input :color, collection: Car::COLORS, include_blank: false %>
    <%= f.input :driver, collection: Car::DRIVERS, include_blank: false %>
    <%= f.input :key, collection: Car::KEYS, include_blank: false %>
    <%= f.submit class: 'form-button' %>
  <% end %>

</div>

app/views/drivers/new.html.erb
<div class="container">


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Race471</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="top">
    <h1>Wagon Race #471🏁</h1>
    <div>
      <%= link_to 'Add a Race Car', new_car_path, class: 'button' %>
    </div>
  </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h1 class="text-center">Wagon Race</h1>
    <hr>
    <!-- You race HTML code here -->

    <table class="racer-table">
      <tr id="player1-race">
        <td class="active"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td id="finish"></td>
      </tr>
      <tr id="player2-race">
        <td class="active"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td id="finish"></td>
      </tr>
    </table>
    <hr>

    <script src="main.js"></script>